world_address = "0x06f65de79296c7b625ec04ce997edc64413dc14ca41008d51835802c27ebdbf1"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"

[events]
raw = true

[indexing]
namespaces = ["bm_0_0_8"]
pending = true
world_block = 2210150
contracts = [
]

# Performance tuning
events_chunk_size = 1024
blocks_chunk_size = 10240
polling_interval = 500
max_concurrent_tasks = 100
