world_address = "0x05b80f79658a591ed007cbb138b57315e0f1822ad21e52a410a735d82d6c1449"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"

[events]
raw = true

[indexing]
namespaces = ["bm_0_1_1"]
pending = true
world_block = 2210150
contracts = [
]

# Performance tuning
events_chunk_size = 1024
blocks_chunk_size = 10240
polling_interval = 500
max_concurrent_tasks = 100
