/**
 * Equipment item ID → human-readable name mapping.
 * Source: Provable-Games/death-mountain loot.cairo (ItemId + ItemString).
 * https://github.com/Provable-Games/death-mountain/blob/358de2fd36de38526bbfb2fbcc5fd205de247918/contracts/src/constants/loot.cairo
 */
export const ITEM_ID_TO_NAME: Record<number, string> = {
  1: 'Pendant',
  2: 'Necklace',
  3: 'Amulet',
  4: 'Silver Ring',
  5: 'Bronze Ring',
  6: 'Platinum Ring',
  7: 'Titanium Ring',
  8: 'Gold Ring',
  9: 'Ghost Wand',
  10: 'Grave Wand',
  11: 'Bone Wand',
  12: 'Wand',
  13: 'Grimoire',
  14: 'Chronicle',
  15: 'Tome',
  16: 'Book',
  17: 'Divine Robe',
  18: 'Silk Robe',
  19: 'Linen Robe',
  20: 'Robe',
  21: 'Shirt',
  22: 'Crown',
  23: 'Divine Hood',
  24: 'Silk Hood',
  25: 'Linen Hood',
  26: 'Hood',
  27: 'Brightsilk Sash',
  28: 'Silk Sash',
  29: 'Wool Sash',
  30: 'Linen Sash',
  31: 'Sash',
  32: 'Divine Slippers',
  33: 'Silk Slippers',
  34: 'Wool Shoes',
  35: 'Linen Shoes',
  36: 'Shoes',
  37: 'Divine Gloves',
  38: 'Silk Gloves',
  39: 'Wool Gloves',
  40: 'Linen Gloves',
  41: 'Gloves',
  42: 'Katana',
  43: 'Falchion',
  44: 'Scimitar',
  45: 'Long Sword',
  46: 'Short Sword',
  47: 'Demon Husk',
  48: 'Dragonskin Armor',
  49: 'Studded Leather Armor',
  50: 'Hard Leather Armor',
  51: 'Leather Armor',
  52: 'Demon Crown',
  53: "Dragon's Crown",
  54: 'War Cap',
  55: 'Leather Cap',
  56: 'Cap',
  57: 'Demonhide Belt',
  58: 'Dragonskin Belt',
  59: 'Studded Leather Belt',
  60: 'Hard Leather Belt',
  61: 'Leather Belt',
  62: 'Demonhide Boots',
  63: 'Dragonskin Boots',
  64: 'Studded Leather Boots',
  65: 'Hard Leather Boots',
  66: 'Leather Boots',
  67: "Demon's Hands",
  68: 'Dragonskin Gloves',
  69: 'Studded Leather Gloves',
  70: 'Hard Leather Gloves',
  71: 'Leather Gloves',
  72: 'Warhammer',
  73: 'Quarterstaff',
  74: 'Maul',
  75: 'Mace',
  76: 'Club',
  77: 'Holy Chestplate',
  78: 'Ornate Chestplate',
  79: 'Plate Mail',
  80: 'Chain Mail',
  81: 'Ring Mail',
  82: 'Ancient Helm',
  83: 'Ornate Helm',
  84: 'Great Helm',
  85: 'Full Helm',
  86: 'Helm',
  87: 'Ornate Belt',
  88: 'War Belt',
  89: 'Plated Belt',
  90: 'Mesh Belt',
  91: 'Heavy Belt',
  92: 'Holy Greaves',
  93: 'Ornate Greaves',
  94: 'Greaves',
  95: 'Chain Boots',
  96: 'Heavy Boots',
  97: 'Holy Gauntlets',
  98: 'Ornate Gauntlets',
  99: 'Gauntlets',
  100: 'Chain Gloves',
  101: 'Heavy Gloves',
};

/**
 * Resolve an equipment item ID to its display name (from death-mountain loot.cairo).
 * Returns the name if known, otherwise the ID as string.
 */
export function itemIdToName(itemId: number | string): string {
  const id = typeof itemId === 'string' ? parseInt(itemId, 10) : itemId;
  if (Number.isNaN(id)) return String(itemId);
  return ITEM_ID_TO_NAME[id] ?? String(id);
}
